### ISSUE TITLE
群组织  下面  -- 定位地址  写错了

### ISSUE THREAD

**Issue by srxboys** [iflytek/Guitar#2]
`heifei，china` 写错了 (黑肥 、 嘿肥 ？？)

应该为

`hefei，china`  (合肥)

---

我不知道怎么反馈给你，你的个人也没有邮箱，只能这里告诉你了。

---

其他建议：
[官网地址] 可以填写
[认证] 图标也可以点亮

**Comment by chenzhiang669** [comment]
嘎嘎。@江林刚

**Comment by chenzhiang669** [comment]
> `heifei，china` 写错了 (黑肥 、 嘿肥 ？？)
> 
> 应该为
> 
> `hefei，china` (合肥)
> 
> 我不知道怎么反馈给你，你的个人也没有邮箱，只能这里告诉你了。
> 
> 其他建议：
> [官网地址] 可以填写
> [认证] 图标也可以点亮

嘎嘎@江林刚
